config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  get '/post/:id', to: 'posts#show', as: 'post'

  get '/data' => 'unsecured_pages#data'

  get '/roulette' => 'static_pages#roulette'

  get '/about' => 'static_pages#about'

  get '/post' => 'posts#post'
  get '/browse' => 'posts#browse'
  get '/submit' => 'posts#new'

  get '/user' => 'users#user'

  get '/results' => 'roulettes#results'

  root 'users#user'
  

  resources :posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :vibes
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :vibes
end

app/models/vibe.rb
class Vibe < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/end_users_base_controller_controller.rb
class EndUsersBaseControllerController < ApplicationController
	before_filter :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@post = Post.new
	end
	
	def create
	  @uploaded_io = params[:posts][:picture]

	  File.open(Rails.root.join('public', 'uploads', @uploaded_io.original_filename), 'wb') do |file|
	    file.write(@uploaded_io.read)

	  @title = params[:posts][:title]
	  @description = params[:posts][:text] 
	  end
	end
	def post
		@posts = Post.all
		@vibes = Vibe.all

		@posts_with_vibes = Post.find_by_sql "SELECT p.id, p.text_content, 
		v.vibe FROM posts p, vibes v WHERE p.id = v.post_id"
	end
	def show
		@id = params[:id]
		@post = Post.find(@id)
		@vibes = Vibe.where(:post_id => @id)
		@comments = Comment.where(:post_id => @id)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	  def sign_up_params
	    params.require(:user).permit(:username, :email, :password, :password_confirmation)
	  end
end

app/controllers/roulettes_controller.rb
class RoulettesController < ApplicationController
	
	@@text_win = false
	@@image_win = false
	@@video_win = false
	@@triple_lottery_event = false

	def results
		# Each variable is either nil or 1, where nil is unchecked and 
		# 1 is checked
		@text_val = params[:text]
		@images_val = params[:images]
		@video_val = params[:video]
		
		# Creates an array of vibes 
		@vibes_list = params[:vibes]
		@vibes_list = @vibes_list.gsub(" ", "")
		@vibes_list = @vibes_list.split(",")

		# Variable for parameter testing
		@test_post = Post.find(14)
		@results_asc = Post.order(views: :asc)
		
		@test_num = count_checkboxes
		
		# Main logic
		roulette_size = 10
		num_checked = count_checkboxes
		posts_per_type = roulette_size / num_checked

		

		if(num_checked == 3)
			@@triple_lottery_event = true

			@@lottery = 1 + rand(3)

			if(@@lottery == 1)
				@@text_win = true
			
			elsif(@@lottery == 2)
				@@image_win = true
			
			elsif(@@lottery == 3)
				@@video_win = true
			end
		end

		text_posts = []
		image_posts = []
		video_posts = []

		if(@text_val)
			
			text_posts = get_text_posts(posts_per_type)
			
			end
		if(@images_val)
			
			image_posts = get_image_posts(posts_per_type)
			
			end
		if(@video_val)
			
			video_posts = get_video_posts(posts_per_type)
			
			end
		

		all_posts = text_posts + image_posts + video_posts
		@result_posts = all_posts.shuffle

	end

	def count_checkboxes
		val_array = [@text_val, @images_val, @video_val]
		counter = 0
		val_array.each do |x|
			if x == "1"
				counter += 1
			end
		end
		return counter
	end

	def get_text_posts(num_posts)

		if(@@triple_lottery_event && @@text_win)
			return result = Post.where(:post_type => "text").limit(num_posts+1)
		end
		# result = Post.where(:post_type => "text").limit(num_posts+1)
		# 	if result == nil
		# 	 	return []
		# 	else 
		# 		return result
		# 	end
		return result = Post.where(:post_type => "text").limit(num_posts)
	end

	def get_image_posts(num_posts)

		if(@@triple_lottery_event && @@text_win)
			return result = Post.where(:post_type => "image").limit(num_posts+1)
		end

		return result = Post.where(:post_type => "image").limit(num_posts)
	end

	def get_video_posts(num_posts)

		if(@@triple_lottery_event && @@text_win)
			return result = Post.where(:post_type => "video").limit(num_posts+1)
		end

		return result = Post.where(:post_type => "video").limit(num_posts)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
	def roulette

	end

	def submit

	end

end

app/controllers/unsecured_pages_controller.rb
class UnsecuredPagesController 
	def splash

	end

	def data
		@posts = Post.all
		@comments = Comment.all
		@vibes = Vibe.all
		@users = User.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def user

	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/end_users_base_controller_helper.rb
module EndUsersBaseControllerHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/roulettes_helper.rb
module RoulettesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/unsecured_pages_helper.rb
module UnsecuredPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/browse.html.erb
<h1>BROWSE STUFF</h1>

app/views/posts/create.html.erb
<!DOCTYPE html>
<html>
    <header>
        <link rel="stylesheet" href="/../app/assets/stylesheets/bootstrap.min.css">
        <link rel="stylesheet" href="/../app/assets/stylesheets/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/../app/assets/stylesheets/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/../app/assets/stylesheets/default.css">
        <script src="./js/jquery-2.1.1.js"></script>
        <script src="./js/bootstrap.min.js"></script>
        <script src="./js/search.js"></script>
        <style>
            .col-md-5 {
                float: none;
                margin: 0 auto;
                text-align: center;
            }
            .col-md-5 div {
                width: 100%;
            }
            #roulette-box {
                border-top: none;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
            #image-box img {
            	width: 100%;
            }
        </style>
    </header>
    <body>
        <div id="wrap">
           
            <div class="container">
                <div class="clearer">&nbsp;</div>
                <div class="row">
                    <div class="col-md-5">
                        <h3>
                            <%= @title %>
                        </h3>
                        <div id="image-box">
                            <%= image_tag "/uploads/#{@uploaded_io.original_filename}" %>
                        </div>
                        <div class="clearer">&nbsp;</div>
                        <div class="desc-box black">
                            <p>
                                <%= @description %>
                            </p>
                        </div>
                        <div class="clearer">&nbsp;</div>
                        <p>
                            Give it a 
                            <input type="submit" value="Spark!">
                        </p>
                            <div class="clearer">&nbsp;</div>
                        <div id="vibe-tab" class="tab">Vibes</div>
                        <div id="comment-tab" class="tab unselected">Comments</div>
                        <div class="clearer"></div>
                        <div class="form-container" id="roulette-box">
                            <div class="clearer">&nbsp;</div>
                            <div class="clearer">&nbsp;</div>
                            <div id="vibe-box">
                                <img src="./images/placeholder_roulette.png"/>
                                <div class="clearer">&nbsp;</div>
                                <form>
                                    <textarea class="long" placeholder="Enter vibes"></textarea>
                                    <div class="clearer">&nbsp;</div>
                                    <input type="submit" value='Submit'/>
                                    <div class="clearer">&nbsp;</div>
                                </form>
                            </div>
                            <div id="comment-box" class="hidden">
                                <form>
                                    <textarea class="long" placeholder="Enter a comment"></textarea>
                                    <div class="clearer">&nbsp;</div>
                                    <input type="submit" value='Submit'/>
                                    <div class="clearer">&nbsp;</div>
                                </form>
                                <ul id="comments">
                                    <li class="comment">
                                        <a class="red-link" href="./~profile-vvvvvvitellary.html">
                                            <h4>
                                                vvvvvvitellary
                                            </h4>
                                        </a>
                                        <p>
                                            Should have stayed away from the pinkish hues on the hilt and handle - makes it look more like a strawberry than a flaming sword.
                                        </p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="clearer">&nbsp;</div>
                        <div class="clearer">&nbsp;</div>
                    </div>
                </div>
        </div>
    </body>
</html> 

app/views/posts/new.html.erb
<% provide(:title, "Submit") %>
<% provide(:selected, ["submit"]) %>
<% content_for :head do %>
<% end %>


<style>
    .col-md-5 {
        float: none;
        margin: 0 auto;
    }
    input[type=file]::before {
        content: "Drag a file in here or";
        top: 4rem;
        left: 0;
        right: 0;
        text-align: center;
        position: absolute;
    }
    input[type=file] {
        padding-left: 15%;
        width: 90%;
        height: auto;
        padding-bottom: 6rem;
    }
    input[type=text], textarea{
        width: 90% !important;
    }

</style>
    <div class="container">
        <div class="clearer">&nbsp;</div>
        <div class="row">
            <div class="col-md-5">
                <div class="form-container">
                    <h3>
                        Submit
                    </h3>
                    <%= form_for :posts, url: posts_path do |f| %>
					<p>
						<%= f.text_field :title, :placeholder => 'title', :required => 'required' %>
					</p>
					<p>
						<%= f.file_field :picture, :required => 'required'%>
					</p>
					<p>
						<%= f.text_area :text, :placeholder => 'Write a description...' %>
					</p>

					<p>
					<%= f.submit "Submit" %>
					</p>
				<% end %>
                </div>
            </div>
            <div class="col-md-3">
            </div>
        </div>
        <div class="clearer">&nbsp;</div>
    </div>

app/views/posts/post.html.erb
<h1>you've come to the right place</h1>

<table>
  <tr>Post</tr>
  <% @posts.each do |elt|%>
    <tr>
      <td><%= elt.id %></td>
      <td><%= elt.text_content %></td>

      <td><%= elt.image_path %></td>
      <td><%= elt.video_path %></td>
      <td><%= elt.spark_count %></td>
      <td><%= elt.score %></td>
      <td><%= elt.views %></td>
    </tr>
  <% end %>
</table>

<br><table>
  <tr>Vibe</tr>
  <% @vibes.each do |elt|%>
    <tr>
      <td><%= elt.id %></td>
      <td><%= elt.vibe %></td>
      <td><%= elt.user_id %></td>
      <td><%= elt.post_id %></td>
    </tr>
  <% end %>
</table>

<br><table>
  <tr>Posts with Vibes</tr>
  
  <% @posts_with_vibes.each do |elt|%>
    <tr>
      <td><%= elt.id %></td>
      <td><%= elt.text_content %></td>
      <td><%= elt.vibe %></td>
      
    </tr>
  <% end %>
</table>

app/views/posts/show.html.erb
<table>
  <tr>Post data</tr>
  	<tr>
  	<td>ID</td><td>Text</td><td>Sparks</td>
  	</tr>
    <tr>
      <td><%= @post.id %></td>
      <td><%= @post.text_content %></td>
      <td><%= @post.spark_count %></td>
    </tr>
</table>
<br>

<table>
	<tr>Vibes of post</tr>
	<tr>
		<td>Post ID</td><td>Vibe</td>
	</tr>
	<% @vibes.each do |v|%>
		<tr>
			<td>
				<%= v.id %>
			</td>
			<td>
	 			<%= v.vibe %>
	 		</td>
		</tr>
	<% end %> 
</table>

<table>
	<tr>Comments of post</tr>
	<tr>
		<td>Comment</td><td>Author</td><td>Post ID</td>
	</tr>
	<% @comments.each do |c|%>
		<tr>
			<td>
				<%= c.text_content%>
			</td>
			<td>
	 			<%= c.author_name %>
	 		</td>
	 		<td>
	 			<%= c.post_id %>
	 		</td>
		</tr>
	<% end %> 
</table>

app/views/roulettes/results.html.erb
<h1>HERE ARE THE RESULTS</h1>

<%= link_to 'TestPost', post_path(@test_post) %>
<h3> NUMBER OF CHECKBOXES CHECKED IS <%= @test_num %> </h3>

<table>
<tr>RESULTS</tr>
	<tr>
      	<td> Post ID </td>
      	<td> Text </td>
      	<td> Video path </td>
      	<td> Image path </td>
    </tr>
	<% @result_posts.each do |elt| %>
    <tr>
    	<td>
    		<%= elt.id %>
    	</td>
    	<td>
    		<%= elt.text_content %>
    	</td>
    	<td>
    		<%= elt.video_path %>
    	</td>
    	<td>
    		<%= elt.image_path %>
    	</td>
    </tr>
    <% end %>
</table>
<br><table>
  <tr>Checkbox values</tr>
 
    <tr>
      	<td><%= @text_val %></td>
      	<td><%= @images_val %></td>
      	<td><%= @video_val %></td>
    </tr>
    <tr>
    	<td><%= @vibes_list %></td>
    </tr>
    <tr>
    	Posts
    </tr>
    <% @results_asc.each do |elt| %>
    <tr>
    	<td>
    		<%= elt.text_content %>
    	</td>
    	<td>
    		<%= elt.views %>
    	</td>
    </tr>
    <% end %>
</table>

app/views/static_pages/data.html.erb
<table>
  <tr>Post</tr>
  <% @posts.each do |elt|%>
    <tr>
      <td><%= elt.text_content %></td>
      <td><%= elt.image_path %></td>
      <td><%= elt.video_path %></td>
      <td><%= elt.spark_count %></td>
      <td><%= elt.score %></td>
      <td><%= elt.views %></td>
    </tr>
  <% end %>
</table>

<br><table>
  <tr>User</tr>
  <% @users.each do |elt|%>
    <tr>
      <td><%= elt.name %></td>
      <td><%= elt.about %></td>
      <td><%= elt.password %></td>
    </tr>
  <% end %>
</table>

<br><table>
  <tr>Comment</tr>
  <% @comments.each do |elt|%>
    <tr>
      <td><%= elt.text_content %></td>
      <td><%= elt.author_name %></td>
      <td><%= elt.date_submitted %></td>
      <td><%= elt.post_id %></td>
    </tr>
  <% end %>
</table>

<br><table>
  <tr>Vibe</tr>
  <% @vibes.each do |elt|%>
    <tr>
      <td><%= elt.vibe %></td>
      <td><%= elt.user_id %></td>
      <td><%= elt.post_id %></td>
    </tr>
  <% end %>
</table>

app/views/static_pages/roulette.html.erb
<!DOCTYPE html>
<html>
    <header>
        <link rel="stylesheet" href="./css/bootstrap.min.css">
        <link rel="stylesheet" href="./css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="./css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="./css/default.css">
        <script src="./js/jquery-2.1.1.js"></script>
        <script src="./js/bootstrap.min.js"></script>
        <style>
            .col-md-5 {
                float: none;
                margin: 0 auto;
            }
            
            #checkboxes{
                width:100%;
				table-layout:fixed;
			}
			input[type=checkbox], select{
				outline: 3px solid #4F2601;
			}
			
			form{
				font-weight:bold;
			}
        </style>
        <script>
        <!-- Should be done with ruby -->
            $(function() {
                $("form").submit(function(evt) {
                    event.preventDefault();
                    window.location = './~roulette_search_image_example2.html';
                });
            });
        </script>
    </header>
    <body>
        <div id="wrap">
            <nav class="navbar navbar-static-top">
              <div class="container">
                <div class="navbar-header">
                  <img id="logo" src="./images/Sparkey Logo Orange.png">
                  <a class="navbar-brand" href="#">
                    Spar<span class="dark-red">k</span>ey
                  </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <div class="navbar-center-wrapper">
                        <ul class="nav navbar-nav navbar-center">
                            <li class="active"><a href="./roulette_config.html">Roulette</a></li>
                            <li><a href="./browse.html">Browse</a></li>
                            <li><a href="./submit.html">Submit</a></li>
                        </ul>
                    </div>
                    <div class="nav navbar-nav navbar-right">
                        <div id="user-options">
                            <a href="./profile.html" class="red-link"> Lassie </a>
                            <span class="divider">|</span>
                            <a href="./splash_page.html" class="red-link"> Logout </a>
                        </div>
                    </div>
                </div><!--/.nav-collapse -->
              </div>
            </nav>
            <div class="container">
                <div class="clearer">&nbsp;</div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-container">
                            <h3>
                                Roulette
                            </h3>
                            <!-- <form>
								<table id="checkboxes">
								<tr>
									<td style="text-align:right"><input type="checkbox" placeholder='title'/> Text</td>
									<td><input type="checkbox" placeholder='title'/> Images</td>
									<td style="text-align:left"><input type="checkbox" placeholder='title'/> Videos</td>
								</table>
                                <div class="clearer">&nbsp;</div>
                                <textarea class="long" placeholder="Enter vibes..."></textarea>
                                <div class="clearer">&nbsp;</div>
								Number of posts:
									<select>
										<option value="10">10</option>
										<option value="20">20</option>
										<option value="30">30</option>
										<option value="40">40</option>
										<option value="50">50</option>
									</select>
								<div class="clearer">&nbsp;</div>
                                <input type="submit" value='Go!' onsubmit="return './~roulette_search_image_example2.html'"/>
                                <div class="clearer">&nbsp;</div>
                            <form> -->
                            <%= form_tag({controller: "roulettes", action: "results"}, method: "get") do %>
                                <%= check_box_tag(:text) %>
                                <%= label_tag(:text, "Text") %>
                                <%= check_box_tag(:images) %>
                                <%= label_tag(:images, "Images") %>
                                <%= check_box_tag(:video) %>
                                <%= label_tag(:video, "Video") %>
                                <%= text_area_tag(:vibes, "", size: "24x6", :placeholder => "Enter vibes...") %>
                                <%= submit_tag("Go!") %>
                            <% end %>
                        </div>
                    </div>
                    <div class="col-md-3">
                    </div>
                </div>
                <div class="clearer">&nbsp;</div>
            </div>
            <!-- Leave push in there, it's for the footer -->
            <div id="push"></div></div>
            <div id="footer">
                <a class="red-link" href="./about.html">About</a>
            </div>
        </div>
    </body>
</html> 

app/views/static_pages/splash.html.erb
<!DOCTYPE html>
<html>
    <header>
        <link rel="stylesheet" href="./css/bootstrap.min.css">
        <link rel="stylesheet" href="./css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="./css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="./css/default.css">
        <script src="./js/jquery-2.1.1.js"></script>
        <script src="./js/bootstrap.min.js"></script>
    </header>
    <body>
        <div id="wrap">
            <nav class="navbar navbar-static-top">
              <div class="container">
                <div class="navbar-header">
                  <img id="logo" src="./images/Sparkey Logo Orange.png">
                  <a class="navbar-brand" href="#">
                    Spar<span class="dark-red">k</span>ey
                  </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                  <div class="nav navbar-nav navbar-right">
                    <form>  
                        <input type="text" placeholder="username"/>
                        <input type="password" placeholder="password"/>
                        <input type="submit" value="Login" />
                    </form>
                    <!-- erb for the login form
                        <%= form_for @user, url: login_path do |f| %>
                            <%= f.text_field :username, :placeholder => "Username" %>
                            <%= f.password_field :password %>
                            <%= f.submit :value => "Login" %>
                        <% end %>
                    -->
                  </div>
                </div>
              </div>
            </nav>
            <div class="container vertical-align">
                <div class="row vertical-align">   
                    <div id="splash_text" class="col-md-5 vertical-align">
                        <div class="black">
                            <p class="big-text">
                                Fed up with your art being <span class="dark-red bold">buried </span> and never getting seen?
                            </p>
                            <p class="big-text">
                                Tired of your voice echoing in an <span class="dark-red bold">empty stadium</span>? </br>
                            </p>
                            <p class="big-text">
                                Join a community whose goal is to <span class="dark-red bold">help</span> each other be heard and where stray <span class="dark-red bold">sparks</span> start <span class="dark-red bold">wildfires</span>! </br>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-2">
                    </div>

                    <div class="col-md-4">
                        <div class="form-container">
                            <h3 >
                                Sign up!
                            </h3>
                            <form>
                                <input class="long" type="text" placeholder='email'/>
                                <div class="clearer">&nbsp;</div>
                                <input class="long" type="text" placeholder='username'/>
                                <div class="clearer">&nbsp;</div>
                                <input class="long" type="password" placeholder='password'/>
                                <div class="clearer">&nbsp;</div>
                                <input class="long" type="password" placeholder='confirm password'/>
                                <div class="clearer">&nbsp;</div>
                                <div class="clearer">&nbsp;</div>
                                <input type="submit" value='Sign Up'/>
                                <div class="clearer">&nbsp;</div>
                                <div class="clearer">&nbsp;</div>
                            <form>
                        </div>
                        <!--For the create, erb
                            <%= form_for :user, url: create_path do |f| %>
                                <%= f.text_field :email, :placeholder => "email"%>
                                <div class="clearer">&nbsp;</div>
                                <%= f.text_field :name, :placeholder => "username"%>
                                <div class="clearer">&nbsp;</div>
                                <%= f.password_field :password, :placeholder => "password"%>
                                <div class="clearer">&nbsp;</div>
                                <%= f.password_field :password_2 :placeholder => "confirm password"%>
                                <div class="clearer">&nbsp;</div>
                                <%= f.submit :value => "Sign Up!" %>
                                <div class="clearer">&nbsp;</div>
                            <% end %>
                            
                            :class => 'submit_class_name_here'
                        -->
                    </div>
                </div>
            </div>
            <!-- Leave push in there, it's for the footer -->
            <div id="push"></div>
        </div>
            <div id="footer">
                <a class="red-link" href="./about.html">About</a>
            </div>
        </div>
    </body>
</html> 

app/views/unsecured_pages/data.html.erb
<table>
  <tr>Post</tr>
  <% @posts.each do |elt|%>
    <tr>
      <td><%= elt.id %></td>
      <td><%= elt.text_content %></td>
      <td><%= elt.image_path %></td>
      <td><%= elt.video_path %></td>
      <td><%= elt.spark_count %></td>
      <td><%= elt.score %></td>
      <td><%= elt.views %></td>
    </tr>
  <% end %>
</table>

<br><table>
  <tr>User</tr>
  <% @users.each do |elt|%>
    <tr>
      <td><%= elt.id %></td>
      <td><%= elt.username %></td>
      <td><%= elt.email %></td>
    </tr>
  <% end %>
</table>

<br><table>
  <tr>Comment</tr>
  <% @comments.each do |elt|%>
    <tr>
      <td><%= elt.id %></td>
      <td><%= elt.text_content %></td>
      <td><%= elt.author_name %></td>
      <td><%= elt.date_submitted %></td>
      <td><%= elt.post_id %></td>
    </tr>
  <% end %>
</table>

<br><table>
  <tr>Vibe</tr>
  <% @vibes.each do |elt|%>
    <tr>
      <td><%= elt.id %></td>
      <td><%= elt.vibe %></td>
      <td><%= elt.user_id %></td>
      <td><%= elt.post_id %></td>
    </tr>
  <% end %>
</table>

app/views/unsecured_pages/splash.html.erb
<% provide(:title, "Sparkey") %>
<% content_for :head do %>
<% end %>

<div class="container vertical-align">
    <div class="row vertical-align">   
        <div id="splash_text" class="col-md-5 vertical-align">
            <div class="black">
                <p class="big-text">
                    Fed up with your art being <span class="dark-red bold">buried </span> and never getting seen?
                </p>
                <p class="big-text">
                    Tired of your voice echoing in an <span class="dark-red bold">empty stadium</span>? </br>
                </p>
                <p class="big-text">
                    Join a community whose goal is to <span class="dark-red bold">help</span> each other be heard and where stray <span class="dark-red bold">sparks</span> start <span class="dark-red bold">wildfires</span>! </br>
                </p>
            </div>
        </div>
        <div class="col-md-2">
        </div>

        <div class="col-md-4">
            <div class="form-container">
                <h3 >
                    Sign up!
                </h3>
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                    <%= devise_error_messages! %>
                     
                        <%= f.email_field :email, autofocus: true, :placeholder => "email", :class => "long" %>
                      
                        <div class="clearer">&nbsp;</div> 
                        <%= f.text_field :username, autocomplete: "off", :placeholder => "username", :class => "long" %>
                        <div class="clearer">&nbsp;</div>

                        <% if @minimum_password_length %>
                        <em>(<%= @minimum_password_length %> characters minimum)</em>
                        <% end %>
                        <%= f.password_field :password, autocomplete: "off", :placeholder => "password", :class => "long" %>
                        <div class="clearer">&nbsp;</div>                    
                      
                        <%= f.password_field :password_confirmation, autocomplete: "off", :placeholder => "confirm password", :class => "long" %>
                        <div class="clearer">&nbsp;</div>

                        <div class="actions">
                            <%= f.submit "Sign up" %>
                        </div>
                        <div class="clearer">&nbsp;</div>
                <% end %>
            </div>
            
        </div>
    </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>