config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  get '/post/:id', to: 'posts#show', as: 'post'

  get '/data' => 'unsecured_pages#data'

  get '/roulette' => 'static_pages#roulette'

  get '/about' => 'static_pages#about'

  get '/post' => 'posts#post'
  get '/browse' => 'posts#browse'
  get '/submit' => 'posts#new'

  get '/user' => 'users#user'

  get '/results' => 'roulettes#results'

  root 'users#user'
  

  resources :posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :vibes
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :vibes
end

app/models/vibe.rb
class Vibe < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@post = Post.new
	end
	
	def create
	  @uploaded_io = params[:posts][:picture]

	  File.open(Rails.root.join('public', 'uploads', @uploaded_io.original_filename), 'wb') do |file|
	    file.write(@uploaded_io.read)

	  @title = params[:posts][:title]
	  @description = params[:posts][:text] 
	  end
	end
	def post
		@posts = Post.all
		@vibes = Vibe.all

		@posts_with_vibes = Post.find_by_sql "SELECT p.id, p.text_content, 
		v.vibe FROM posts p, vibes v WHERE p.id = v.post_id"
	end
	def show
		@id = params[:id]
		@post = Post.find(@id)
		@vibes = Vibe.where(:post_id => @id)
		@comments = Comment.where(:post_id => @id)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	  def sign_up_params
	    params.require(:user).permit(:username, :email, :password, :password_confirmation)
	  end
end

app/controllers/roulettes_controller.rb
class RoulettesController < ApplicationController
	
	@@text_win = false
	@@image_win = false
	@@video_win = false
	@@triple_lottery_event = false

	def results
		# Each variable is either nil or 1, where nil is unchecked and 
		# 1 is checked
		@text_val = params[:text]
		@images_val = params[:images]
		@video_val = params[:video]
		
		# Creates an array of vibes 
		@vibes_list = params[:vibes]
		@vibes_list = @vibes_list.gsub(" ", "")
		@vibes_list = @vibes_list.split(",")

		# Variable for parameter testing
		@test_post = Post.find(14)
		@results_asc = Post.order(views: :asc)
		
		@test_num = count_checkboxes
		
		# Main logic
		roulette_size = 10
		num_checked = count_checkboxes
		posts_per_type = roulette_size / num_checked

		

		if(num_checked == 3)
			@@triple_lottery_event = true

			@@lottery = 1 + rand(3)

			if(@@lottery == 1)
				@@text_win = true
			
			elsif(@@lottery == 2)
				@@image_win = true
			
			elsif(@@lottery == 3)
				@@video_win = true
			end
		end

		text_posts = []
		image_posts = []
		video_posts = []

		if(@text_val)
			
			text_posts = get_text_posts(posts_per_type)
			
			end
		if(@images_val)
			
			image_posts = get_image_posts(posts_per_type)
			
			end
		if(@video_val)
			
			video_posts = get_video_posts(posts_per_type)
			
			end
		

		all_posts = text_posts + image_posts + video_posts
		@result_posts = all_posts.shuffle

	end

	def count_checkboxes
		val_array = [@text_val, @images_val, @video_val]
		counter = 0
		val_array.each do |x|
			if x == "1"
				counter += 1
			end
		end
		return counter
	end

	def get_text_posts(num_posts)

		if(@@triple_lottery_event && @@text_win)
			return result = Post.where(:post_type => "text").limit(num_posts+1)
		end
		# result = Post.where(:post_type => "text").limit(num_posts+1)
		# 	if result == nil
		# 	 	return []
		# 	else 
		# 		return result
		# 	end
		return result = Post.where(:post_type => "text").limit(num_posts)
	end

	def get_image_posts(num_posts)

		if(@@triple_lottery_event && @@text_win)
			return result = Post.where(:post_type => "image").limit(num_posts+1)
		end

		return result = Post.where(:post_type => "image").limit(num_posts)
	end

	def get_video_posts(num_posts)

		if(@@triple_lottery_event && @@text_win)
			return result = Post.where(:post_type => "video").limit(num_posts+1)
		end

		return result = Post.where(:post_type => "video").limit(num_posts)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
	def roulette

	end

	def submit

	end

end

app/controllers/unsecured_pages_controller.rb
class UnsecuredPagesController 
	def splash

	end

	def data
		@posts = Post.all
		@comments = Comment.all
		@vibes = Vibe.all
		@users = User.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def user

	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/roulettes_helper.rb
module RoulettesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/unsecured_pages_helper.rb
module UnsecuredPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
    <a class="red-link" href="./about.html">About</a>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
	<nav class="navbar navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<%= image_tag("Sparkey Logo Orange.png", :alt => "Sparkey", :id => "logo") %>
				<a class="navbar-brand" href="#">
					Spar<span class="dark-red">k</span>ey
				</a>
			</div>
		<div id="navbar" class="navbar-collapse collapse">
			<div class="navbar-center-wrapper">
				<ul class="nav navbar-nav navbar-center">
					<% selected = yield(:selected) %>
					<% if selected.include? "roulette" %>
					    <li class="active"><a href="./roulette_config.html">Roulette</a></li>
					    <li><a href="./browse.html">Browse</a></li>
				    	<li><a href="./submit.html">Submit</a></li>
			    	<% else %>
		    			<li><a href="./roulette_config.html">Roulette</a></li>
				    	<% if selected.include? "browse"%>
					    	<li class="active"><a href="./browse.html">Browse</a></li>
					    	<li><a href="./submit.html">Submit</a></li>
					  	<% else %>
				  			<li><a href="./browse.html">Browse</a></li>
					  		<% if selected.include? "submit"%>
				  				<li class="active"><a href="./submit.html">Submit</a></li>
			  				<% else %>
		  						<li><a href="./submit.html">Submit</a></li>
			  				<% end %>
						<% end %>
					<% end %>
				</ul>
			</div>
			<div class="nav navbar-nav navbar-right">
				<div id="user-options">
				    <a href="./profile.html" class="red-link"> <%= current_user.username %> </a>
				    <span class="divider">|</span>
				    <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "red-link") %>
				</div>
			</div>
		</div><!--/.nav-collapse -->
		</div>
	</nav>

<% else %>
	<nav class="navbar navbar-static-top">
	  <div class="container">
	    <div class="navbar-header">
	      <%= image_tag("Sparkey Logo Orange.png", :alt => "Sparkey", :id => "logo") %>
	      <a class="navbar-brand" href="#">
	        Spar<span class="dark-red">k</span>ey
	      </a>
	    </div>
	    <div id="navbar" class="navbar-collapse collapse">
	      <div class="nav navbar-nav navbar-right">
			 <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
			    <%= f.email_field :email, autofocus: true, :placeholder => "email" %>
			 
			    <%= f.password_field :password, autocomplete: "off", :placeholder => "password" %>
			 
			    <%= f.submit "Login" %>
			 <% end %>
	      </div>
	    </div>
	  </div>
	</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>
			<%= yield(:title) %>
		</title>
		<%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag "bootstrap.min.css", "bootstrap-theme.min.css", "default.css" %>
        <%= javascript_include_tag "jquery-2.1.1.js", "bootstrap.min.js" %>
		<%= csrf_meta_tags %>
		<%= yield :head %>
	</head>
	<body>
		<div id="wrap">
			<%= render 'layouts/header' %>

			<%= yield %>
			<div id="push"></div>
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>